name: release-tag

on:
  create:
    tags:
      - v* # только теги начинающиеся с v: v1, v2, v5

env:
  APP_IMAGE_NAME: ukatherine/devops-example-app

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Скачиваем образ
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest
      # Тегируем, тег в образе совпадает с тегом git-репозитория
      # github.ref_name - в данном случае имя тега
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Заливаем новый тег
      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}
      - run: docker pull ukatherine/devops-example-caddy:latest
      - run: docker tag ukatherine/devops-example-caddy:latest ukatherine/devops-example-caddy:${{ github.ref_name }}
      - run: docker push ukatherine/devops-example-caddy:${{ github.ref_name }}
